### ISSUE TITLE
Reference error: window is not defined

### ISSUE THREAD

**Issue by grrrwaaa** [Looking-Glass/bridge.js#30]
I created a new Node.js project and inserted the example code as per README:

```js
import {BridgeClient} from '@lookingglass/bridge'

const Bridge = BridgeClient.getInstance()

async function run() {
    await Bridge.connect()
    console.log("ok")
}
run()
```

Result:

```
ReferenceError: window is not defined
    at ct (C:\Users\alice\Documents\anode_lookingglass\node_modules\@lookingglass\bridge\dist\looking-glass-bridge.js:1:2962)
    at dt.connectToBridgeEventSource (C:\Users\alice\Documents\anode_lookingglass\node_modules\@lookingglass\bridge\dist\looking-glass-bridge.js:1:4627)
    at T.subscribeToEvents (C:\Users\alice\Documents\anode_lookingglass\node_modules\@lookingglass\bridge\dist\looking-glass-bridge.js:1:80823)
    at T.connect (C:\Users\alice\Documents\anode_lookingglass\node_modules\@lookingglass\bridge\dist\looking-glass-bridge.js:1:71163) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///C:/Users/alice/Documents/anode_lookingglass/test.mjs:12:5)

Node.js v20.18.0
```

Is this module only designed to work in a browser context? 

I have another Node.js project that generates OpenGL scenes directly and want to view them on the Looking Glass. I am able to create a fullscreen undecorated window in my Node.js script and I can see this on the Looking Glass.  I assumed that I needed to use Bridge to get the appropriate calibration data for the shaders to create the quilt.  Is this possible via the '@lookingglass/bridge' node module?

**Comment by BryanChrisBrown** [comment]
Can you try this PR here? https://github.com/Looking-Glass/bridge.js/pull/21

Definitely curious to learn more about your project that runs OpenGL directly, we've got a lower level bridge api using shared textures that might be exciting to try there!

**Comment by grrrwaaa** [comment]
Will definitely try when I get back to the lab next week, tha k you!

And yes, if there's a shared texture workflow possible that would probably be even better! Is that documented somewhere yet?

Thanks!

**Comment by BryanChrisBrown** [comment]
@grrrwaaa The Bridge SDK documentation is available here: https://docs.lookingglassfactory.com/core/looking-glass-bridge-sdk

let me know if you get a chance to try the PR or if you hit any other issues with the SDK itself.
